In [1]:
import sys
sys.executable

'C:\\Users\\SEAN\\anaconda3\\envs\\Carbon_Cloud\\python.exe'

In [2]:
# Importing required libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
# Creating a dataframe
transport_df = pd.read_csv("Transportation_Preprocessed_Dataset.csv")
transport_df.head(50)

,make,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb,fuel_consumption_comb_mpg,co2_emissions
0,ACURA,UDV,2.0,4,AS,Z,9.9,6.7,8.5,33,196
1,ACURA,UDV,2.4,4,M,Z,11.2,7.7,9.6,29,221
2,ACURA,UDV,1.5,4,AV,Z,6.0,5.8,5.9,48,136
3,ACURA,UDV,3.5,6,AS,Z,12.7,9.1,11.1,25,255
4,ACURA,UDV,3.5,6,AS,Z,12.1,8.7,10.6,27,244
5,ACURA,SDV,3.5,6,AS,Z,11.9,7.7,10.0,28,230
6,ACURA,SDV,3.5,6,AS,Z,11.8,8.1,10.1,28,232
7,ACURA,SDV,3.7,6,AS,Z,12.8,9.0,11.1,25,255
8,ACURA,SDV,3.7,6,M,Z,13.4,9.5,11.6,24,267
9,ACURA,UDV,2.4,4,AS,Z,10.6,7.5,9.2,31,212
10,ACURA,UDV,2.4,4,M,Z,11.2,8.1,9.8,29,225
11,ACURA,UDV,3.5,6,AS,Z,12.1,8.3,10.4,27,239
12,ALFA ROMEO,UDV,1.8,4,AM,Z,9.7,6.9,8.4,34,193
13,ASTON MARTIN,UDV,5.9,12,A,Z,18.0,12.6,15.6,18,359
14,ASTON MARTIN,UDV,5.9,12,A,Z,18.0,12.6,15.6,18,359
15,ASTON MARTIN,UDV,4.7,8,AM,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,UDV,4.7,8,M,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,UDV,4.7,8,AM,Z,17.4,11.3,14.7,19,338
18,ASTON MARTIN,UDV,4.7,8,M,Z,18.1,12.2,15.4,18,354
19,ASTON MARTIN,UDV,5.9,12,A,Z,18.0,12.6,15.6,18,359
20,AUDI,UDV,2.0,4,AV,Z,9.9,7.4,8.8,32,202
21,AUDI,UDV,2.0,4,AS,Z,11.5,8.1,10.0,28,230
22,AUDI,UDV,2.0,4,M,Z,10.8,7.5,9.3,30,214
23,AUDI,UDV,2.0,4,AS,Z,11.5,8.1,10.0,28,230
24,AUDI,UDV,2.0,4,AS,Z,11.5,8.1,10.0,28,230
25,AUDI,UDV,2.0,4,M,Z,10.8,7.5,9.3,30,214
26,AUDI,SDV,2.0,4,AS,Z,12.0,8.1,10.2,28,235
27,AUDI,SDV,3.0,6,AS,Z,12.8,8.6,10.9,26,251
28,AUDI,SDV,3.0,6,AS,D,9.8,6.2,8.1,35,217
29,AUDI,SDV,3.0,6,AS,Z,13.3,8.5,11.2,25,262
30,AUDI,SDV,3.0,6,AS,D,9.8,6.2,8.1,35,217
31,AUDI,SDV,3.0,6,AS,Z,13.1,8.8,11.2,25,258
32,AUDI,SDV,4.0,8,AS,Z,13.7,8.3,11.3,25,265
33,AUDI,SDV,3.0,6,AS,D,9.8,6.5,8.4,34,224
34,AUDI,SDV,3.0,6,AS,Z,13.1,8.8,11.2,25,258
35,AUDI,SDV,4.0,8,AS,Z,14.7,9.7,12.5,23,288
36,AUDI,SDV,6.3,12,AS,Z,18.7,11.5,15.5,18,363
37,AUDI,SDV,3.0,6,AS,D,9.8,6.5,8.4,34,224
38,AUDI,SV,2.0,4,AS,Z,11.8,8.8,10.5,27,242
39,AUDI,UDV,2.0,4,AS,Z,12.0,8.5,10.4,27,239
40,AUDI,UDV,3.0,6,AS,Z,12.9,9.2,11.2,25,258
41,AUDI,UDV,3.0,6,AS,D,10.2,7.8,9.0,31,244
42,AUDI,UDV,2.0,4,AS,Z,9.9,8.3,9.2,31,212
43,AUDI,SDV,3.0,6,AS,Z,15.1,10.9,13.2,21,304
44,AUDI,SDV,3.0,6,AS,D,12.4,8.7,10.7,26,290
45,AUDI,UDV,4.2,8,A,Z,17.6,11.0,14.6,19,336
46,AUDI,UDV,4.2,8,M,Z,21.2,13.4,17.7,16,407
47,AUDI,UDV,5.2,10,A,Z,18.2,10.6,14.8,19,347
48,AUDI,UDV,5.2,10,M,Z,21.1,13.8,17.8,16,409
49,AUDI,UDV,4.2,8,A,Z,17.6,11.0,14.6,19,336

In [4]:
transport_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7384 entries, 0 to 7383
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   make                       7384 non-null   object
 1   vehicle_class              7384 non-null   object
 2   engine_size                7384 non-null   float64
 3   cylinders                  7384 non-null   int64
 4   transmission               7384 non-null   object
 5   fuel_type                  7384 non-null   object
 6   fuel_consumption_city      7384 non-null   float64
 7   fuel_consumption_hwy       7384 non-null   float64
 8   fuel_consumption_comb      7384 non-null   float64
 9   fuel_consumption_comb_mpg  7384 non-null   int64
 10  co2_emissions              7384 non-null   int64
dtypes: float64(4), int64(3), object(4)
memory usage: 634.7+ KB

In [5]:
# Qualitative / Categorical Variables :- make, model, vehicle_class, transmission, fuel_type
transport_df_qualitative = transport_df.drop(['engine_size','cylinders','fuel_consumption_city', 'fuel_consumption_hwy', 'fuel_consumption_comb', 'fuel_consumption_comb_mpg', 'co2_emissions'], axis=1)

In [6]:
# Visualizing unique_categories_count & Observations/sample_count for each categories related to all Qualitative Variables
for i in transport_df_qualitative.columns:
    category_count = transport_df[i].value_counts()
    print(category_count)
    print("Unique categories count for", i ,":",transport_df[i].nunique())
    print()

make
FORD             628
CHEVROLET        587
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64
Unique categories count for make : 42

vehicle_class
UDV    3631
SDV    2506
DT      697
SV      382
CDV     168
Name: count, dtype: int64
Unique categories count for vehicle_class : 5

transmission
AS    3126
A     1851
M     1185
AM     646
AV     576
Name: count, dtype: int64
Unique categories count for transmission : 5

fuel_type
X    3637
Z    3202
E     370
D     175
Name: count, dtype: int64
Unique categories count for fuel_type : 4

In [7]:
## Encoding technique that should be use for each Categorical Variables are listed below
# make (42 categories) => Hash Encoding
# vehicle_class (5 categories) => Dummy Encoding
# transmission (5 categories) => Dummy Encoding
# fuel_type (4 categories) => Dummy Encoding

In [8]:
# Encoding categorical variable "make" using Hash Encoding.

import category_encoders as ce

# Initialize HashingEncoder
hash_encoder = ce.HashingEncoder(cols=['make'], n_components=4)  # Adjust n_components as needed

# Fit and transform the data
hash_encoded = hash_encoder.fit_transform(transport_df['make'])

# Get the names of the resulting columns
column_names = hash_encoder.get_feature_names_out()

# Concatenate original column name with the resulting column names
hash_encoded.columns = [f"{transport_df.columns[0]}_{col}" for col in column_names]

# Concatenate original DataFrame with hash-encoded DataFrame
transport_df = pd.concat([transport_df, hash_encoded], axis=1)
transport_df

,make,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb,fuel_consumption_comb_mpg,co2_emissions,make_col_0,make_col_1,make_col_2,make_col_3
0,ACURA,UDV,2.0,4,AS,Z,9.9,6.7,8.5,33,196,0,0,0,1
1,ACURA,UDV,2.4,4,M,Z,11.2,7.7,9.6,29,221,0,0,0,1
2,ACURA,UDV,1.5,4,AV,Z,6.0,5.8,5.9,48,136,0,0,0,1
3,ACURA,UDV,3.5,6,AS,Z,12.7,9.1,11.1,25,255,0,0,0,1
4,ACURA,UDV,3.5,6,AS,Z,12.1,8.7,10.6,27,244,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7379,VOLVO,UDV,2.0,4,AS,Z,10.7,7.7,9.4,30,219,0,0,1,0
7380,VOLVO,UDV,2.0,4,AS,Z,11.2,8.3,9.9,29,232,0,0,1,0
7381,VOLVO,UDV,2.0,4,AS,Z,11.7,8.6,10.3,27,240,0,0,1,0
7382,VOLVO,SDV,2.0,4,AS,Z,11.2,8.3,9.9,29,232,0,0,1,0
7383,VOLVO,SDV,2.0,4,AS,Z,12.2,8.7,10.7,26,248,0,0,1,0

In [9]:
# Encoding categorical variables "vehicle_class" using Dummy Encoding.
dummy_encoded_vehicle_class = pd.get_dummies(transport_df['vehicle_class'], drop_first=True, prefix='vehicle_class')
# Convert "True / False" to "1 / 0"
dummy_encoded_vehicle_class = dummy_encoded_vehicle_class.astype(int)
# Concatenate original DataFrame with vehicle_class dummy-encoded DataFrame
transport_df = pd.concat([transport_df, dummy_encoded_vehicle_class], axis=1)

# Encoding categorical variables "transmission" using Dummy Encoding.
dummy_encoded_transmission = pd.get_dummies(transport_df['transmission'], drop_first=True, prefix='transmission')
# Convert "True / False" to "1 / 0"
dummy_encoded_transmission = dummy_encoded_transmission.astype(int)
# Concatenate original DataFrame with transmission dummy-encoded DataFrame
transport_df = pd.concat([transport_df, dummy_encoded_transmission], axis=1)

# Encoding categorical variables "fuel_type"  using Dummy Encoding.
dummy_encoded_fuel_type = pd.get_dummies(transport_df['fuel_type'], drop_first=True, prefix='fuel_type')
# Convert "True / False" to "1 / 0"
dummy_encoded_fuel_type = dummy_encoded_fuel_type.astype(int)
# Concatenate original DataFrame with transmission dummy-encoded DataFrame
transport_df = pd.concat([transport_df, dummy_encoded_fuel_type], axis=1)

In [10]:
# Removing the original categorical variable from the dataframe. "make", "vehicle_class", "transmission", "fuel_type"
transport_df = transport_df.drop(['make', 'vehicle_class', 'transmission', 'fuel_type'], axis=1)
transport_df

,engine_size,cylinders,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb,fuel_consumption_comb_mpg,co2_emissions,make_col_0,make_col_1,make_col_2,...,vehicle_class_SDV,vehicle_class_SV,vehicle_class_UDV,transmission_AM,transmission_AS,transmission_AV,transmission_M,fuel_type_E,fuel_type_X,fuel_type_Z
0,2.0,4,9.9,6.7,8.5,33,196,0,0,0,...,0,0,1,0,1,0,0,0,0,1
1,2.4,4,11.2,7.7,9.6,29,221,0,0,0,...,0,0,1,0,0,0,1,0,0,1
2,1.5,4,6.0,5.8,5.9,48,136,0,0,0,...,0,0,1,0,0,1,0,0,0,1
3,3.5,6,12.7,9.1,11.1,25,255,0,0,0,...,0,0,1,0,1,0,0,0,0,1
4,3.5,6,12.1,8.7,10.6,27,244,0,0,0,...,0,0,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7379,2.0,4,10.7,7.7,9.4,30,219,0,0,1,...,0,0,1,0,1,0,0,0,0,1
7380,2.0,4,11.2,8.3,9.9,29,232,0,0,1,...,0,0,1,0,1,0,0,0,0,1
7381,2.0,4,11.7,8.6,10.3,27,240,0,0,1,...,0,0,1,0,1,0,0,0,0,1
7382,2.0,4,11.2,8.3,9.9,29,232,0,0,1,...,1,0,0,0,1,0,0,0,0,1
7383,2.0,4,12.2,8.7,10.7,26,248,0,0,1,...,1,0,0,0,1,0,0,0,0,1

In [11]:
# Column to be moved to the last position
column_to_move = 'co2_emissions'

# Pop the column from its original position and insert it at the last position
column = transport_df.pop(column_to_move)
transport_df.insert(len(transport_df.columns), column.name, column)
transport_df

,engine_size,cylinders,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb,fuel_consumption_comb_mpg,make_col_0,make_col_1,make_col_2,make_col_3,...,vehicle_class_SV,vehicle_class_UDV,transmission_AM,transmission_AS,transmission_AV,transmission_M,fuel_type_E,fuel_type_X,fuel_type_Z,co2_emissions
0,2.0,4,9.9,6.7,8.5,33,0,0,0,1,...,0,1,0,1,0,0,0,0,1,196
1,2.4,4,11.2,7.7,9.6,29,0,0,0,1,...,0,1,0,0,0,1,0,0,1,221
2,1.5,4,6.0,5.8,5.9,48,0,0,0,1,...,0,1,0,0,1,0,0,0,1,136
3,3.5,6,12.7,9.1,11.1,25,0,0,0,1,...,0,1,0,1,0,0,0,0,1,255
4,3.5,6,12.1,8.7,10.6,27,0,0,0,1,...,0,1,0,1,0,0,0,0,1,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7379,2.0,4,10.7,7.7,9.4,30,0,0,1,0,...,0,1,0,1,0,0,0,0,1,219
7380,2.0,4,11.2,8.3,9.9,29,0,0,1,0,...,0,1,0,1,0,0,0,0,1,232
7381,2.0,4,11.7,8.6,10.3,27,0,0,1,0,...,0,1,0,1,0,0,0,0,1,240
7382,2.0,4,11.2,8.3,9.9,29,0,0,1,0,...,0,0,0,1,0,0,0,0,1,232
7383,2.0,4,12.2,8.7,10.7,26,0,0,1,0,...,0,0,0,1,0,0,0,0,1,248

In [12]:
# Writing the Encoded transport_df to a CSV file
transport_df.to_csv('Transportation_Encoded_Dataset.csv', index=False)